import argentina from "../img/content/flags/argentina.png"
import russia from "../img/content/flags/russia.png"
import brazil from "../img/content/flags/brazil.png"
import france from "../img/content/flags/france.png"
import belgium from "../img/content/flags/belgium.png"
import netherlands from "../img/content/flags/netherlands.png"
import sweden from "../img/content/flags/sweden.png"
import nigeria from "../img/content/flags/nigeria.png"

export const mockApi = [
    {
        id: 0,
        name: "A. Selikhov",
        position: { full: "Goalkeeper", short: "GK" },
        number: 57,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 63,
            sprintSpeed: 67,
            positioning: 56,
            shotPower: 74,
            penalties: 75,
            vision: 72,
            crossing: 76,
            shortPassing: 76,
            longPassing: 70,
            agility: 75,
            reactions: 74,
            ballControl: 81,
            dribbling: 82,
            intercptions: 71,
            stamina: 78,
            strength: 68,
        },
    },
    {
        id: 1,
        name: "Ayrton",
        position: { full: "Left Back", short: "LB" },
        number: 6,
        flag: brazil,
        checked: false,
        stats: {
            acceleration: 86,
            sprintSpeed: 83,
            positioning: 67,
            shotPower: 66,
            penalties: 44,
            vision: 59,
            crossing: 71,
            shortPassing: 68,
            longPassing: 59,
            agility: 77,
            reactions: 73,
            ballControl: 73,
            dribbling: 78,
            intercptions: 65,
            stamina: 59,
            strength: 70,
        },
    },
    {
        id: 2,
        name: "G. Dzhikiya",
        position: { full: "Left Back", short: "LB" },
        number: 14,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 82,
            sprintSpeed: 75,
            positioning: 65,
            shotPower: 74,
            penalties: 45,
            vision: 50,
            crossing: 58,
            shortPassing: 65,
            longPassing: 67,
            agility: 55,
            reactions: 72,
            ballControl: 58,
            dribbling: 69,
            intercptions: 78,
            stamina: 72,
            strength: 86,
        },
    },
    {
        id: 3,
        name: "S. Gigot",
        position: { full: "Centre Back", short: "CB" },
        number: 2,
        flag: france,
        checked: false,
        stats: {
            acceleration: 63,
            sprintSpeed: 70,
            positioning: 51,
            shotPower: 44,
            penalties: 56,
            vision: 55,
            crossing: 68,
            shortPassing: 70,
            longPassing: 73,
            agility: 61,
            reactions: 76,
            ballControl: 65,
            dribbling: 55,
            intercptions: 77,
            stamina: 71,
            strength: 83,
        },
    },
    {
        id: 4,
        name: "M. Caufriez",
        position: { full: "Centre Back", short: "CB" },
        number: 3,
        flag: belgium,
        checked: false,
        stats: {
            acceleration: 53,
            sprintSpeed: 60,
            positioning: 22,
            shotPower: 42,
            penalties: 33,
            vision: 54,
            crossing: 58,
            shortPassing: 62,
            longPassing: 57,
            agility: 38,
            reactions: 63,
            ballControl: 61,
            dribbling: 56,
            intercptions: 66,
            stamina: 66,
            strength: 76,
        },
    },
    {
        id: 5,
        name: "Q. Promes",
        position: { full: "Left Forward", short: "LF" },
        number: 24,
        flag: netherlands,
        checked: false,
        stats: {
            acceleration: 87,
            sprintSpeed: 88,
            positioning: 81,
            shotPower: 81,
            penalties: 74,
            vision: 81,
            crossing: 78,
            shortPassing: 79,
            longPassing: 73,
            agility: 85,
            reactions: 82,
            ballControl: 80,
            dribbling: 81,
            intercptions: 38,
            stamina: 81,
            strength: 64,
        },
    },
    {
        id: 6,
        name: "N. Umyarov",
        position: { full: "Centre Midfield", short: "CM" },
        number: 18,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 63,
            sprintSpeed: 64,
            positioning: 44,
            shotPower: 56,
            penalties: 52,
            vision: 67,
            crossing: 56,
            shortPassing: 73,
            longPassing: 68,
            agility: 61,
            reactions: 67,
            ballControl: 74,
            dribbling: 68,
            intercptions: 66,
            stamina: 72,
            strength: 59,
        },
    },
    {
        id: 7,
        name: "M. Ignatov",
        position: { full: "Centre Midfield", short: "CM" },
        number: 22,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 65,
            sprintSpeed: 68,
            positioning: 50,
            shotPower: 54,
            penalties: 60,
            vision: 67,
            crossing: 56,
            shortPassing: 73,
            longPassing: 68,
            agility: 61,
            reactions: 67,
            ballControl: 74,
            dribbling: 72,
            intercptions: 35,
            stamina: 52,
            strength: 57,
        },
    },
    {
        id: 8,
        name: "A. Lomovitsky",
        position: { full: "Centre Midfield", short: "CM" },
        number: 17,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 79,
            sprintSpeed: 78,
            positioning: 60,
            shotPower: 65,
            penalties: 67,
            vision: 58,
            crossing: 63,
            shortPassing: 66,
            longPassing: 62,
            agility: 71,
            reactions: 54,
            ballControl: 68,
            dribbling: 75,
            intercptions: 21,
            stamina: 52,
            strength: 53,
        },
    },
    {
        id: 9,
        name: "J. Larsson",
        position: { full: "Centre Forward", short: "CF" },
        number: 11,
        flag: sweden,
        checked: false,
        stats: {
            acceleration: 85,
            sprintSpeed: 84,
            positioning: 76,
            shotPower: 80,
            penalties: 65,
            vision: 75,
            crossing: 68,
            shortPassing: 80,
            longPassing: 68,
            agility: 82,
            reactions: 75,
            ballControl: 78,
            dribbling: 80,
            intercptions: 38,
            stamina: 78,
            strength: 69,
        },
    },
    {
        id: 10,
        name: "A. Sobolev",
        position: { full: "Centre Forward", short: "CF" },
        number: 7,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 70,
            sprintSpeed: 72,
            positioning: 75,
            shotPower: 80,
            penalties: 74,
            vision: 65,
            crossing: 35,
            shortPassing: 72,
            longPassing: 45,
            agility: 66,
            reactions: 73,
            ballControl: 72,
            dribbling: 73,
            intercptions: 28,
            stamina: 66,
            strength: 78,
        },
    },
    {
        id: 11,
        name: "V. Moses",
        position: { full: "Right Midfield", short: "RM" },
        number: 8,
        flag: nigeria,
        checked: false,
        stats: {
            acceleration: 77,
            sprintSpeed: 76,
            positioning: 73,
            shotPower: 74,
            penalties: 75,
            vision: 72,
            crossing: 76,
            shortPassing: 76,
            longPassing: 70,
            agility: 75,
            reactions: 74,
            ballControl: 81,
            dribbling: 82,
            intercptions: 71,
            stamina: 78,
            strength: 68,
        },
    },
    {
        id: 12,
        name: "R. Zobnin",
        position: { full: "Centre Midfield", short: "CM" },
        number: 47,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 74,
            sprintSpeed: 78,
            positioning: 68,
            shotPower: 68,
            penalties: 67,
            vision: 72,
            crossing: 73,
            shortPassing: 78,
            longPassing: 76,
            agility: 70,
            reactions: 77,
            ballControl: 81,
            dribbling: 77,
            intercptions: 73,
            stamina: 90,
            strength: 66,
        },
    },
    {
        id: 13,
        name: "Z. Bakaev",
        position: { full: "Centre Midfield", short: "CM" },
        number: 10,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 86,
            sprintSpeed: 85,
            positioning: 70,
            shotPower: 71,
            penalties: 63,
            vision: 78,
            crossing: 67,
            shortPassing: 72,
            longPassing: 67,
            agility: 76,
            reactions: 73,
            ballControl: 70,
            dribbling: 79,
            intercptions: 78,
            stamina: 66,
            strength: 62,
        },
    },
    {
        id: 14,
        name: "A. Eschenko",
        position: { full: "Left Back", short: "LB" },
        number: 38,
        flag: russia,
        checked: false,
        stats: {
            acceleration: 66,
            sprintSpeed: 67,
            positioning: 65,
            shotPower: 56,
            penalties: 55,
            vision: 69,
            crossing: 71,
            shortPassing: 64,
            longPassing: 70,
            agility: 78,
            reactions: 66,
            ballControl: 69,
            dribbling: 58,
            intercptions: 72,
            stamina: 68,
            strength: 67,
        },
    },
    {
        id: 15,
        name: "E. Ponce",
        position: { full: "Centre Forward", short: "CF" },
        number: 9,
        flag: argentina,
        checked: false,
        stats: {
            acceleration: 78,
            sprintSpeed: 76,
            positioning: 75,
            shotPower: 76,
            penalties: 66,
            vision: 57,
            crossing: 59,
            shortPassing: 65,
            longPassing: 50,
            agility: 75,
            reactions: 73,
            ballControl: 73,
            dribbling: 74,
            intercptions: 29,
            stamina: 74,
            strength: 74,
        },
    },
]
